### ISSUE TITLE
Flytta inloggningsknappen

### ISSUE THREAD

**Issue by davidsoderberg** [jh222xk/toerh#10]
Inloggningsknappen bör ligga före "no acount?" så man enkelt kan tabba sig från lösenordsrutan och klicka enter direkt.

**Comment by jh222xk** [comment]
Bra feedback! Ska fixa!

**Comment by jh222xk** [comment]
Åtgärdat i: https://github.com/jh222xk/toerh/commit/f03316d14100db2841b6498248491a1560ea3600
