### ISSUE TITLE
Peer review 1 - kl222jy

### ISSUE THREAD

**Issue by kristofferlind** [jh222xk/toerh#11]
# Peer review 1
Till att börja med ska nämnas att jag aldrig rört varken python eller django, men jag ska göra ett tappert försök.

## Installation
Fick fel om secret key under installation, satte en key i settings.py vilket fungerade. Ser att du sedan fixat readme, toppen.
Bra instruktioner, smärtfri installation.

## Säkerhet
Du har missat att ta bort cookies vid utloggning. Det går dessutom både att visa vyn /tokens och ta bort token även efter att man både loggat ut och manuellt plockat bort cookies. Ytterligare inloggning bekräftar att nyckeln faktiskt är borta.

## Kod
Lagom kommenterad, inga större problem att följa koden där kommentarer saknas. Vissa delar av koden känns väldigt kompakt, kanske måste se ut  så och annars är det väl bara en smaksak.

## Design
Stilren design och behagliga färger. Hade lite problem att hitta admingränssnitt(missade instruktionen), men hittade sedan via kod.

Väldigt välgjort både gällande tester, design och setup med testning via travis. Lycka till med projektet!

**Comment by jh222xk** [comment]
Tack så mycket för detta! Åtgärdat i commit: https://github.com/jh222xk/toerh/commit/560e641ce520bcd17304e0d90fe209fcf9f67c7b
