### ISSUE TITLE
Miss i instruktionerna

### ISSUE THREAD

**Issue by Pajn** [jh222xk/toerh#16]
Jag blev tvungen att installera geospatial libraries `https://docs.djangoproject.com/en/1.7/ref/contrib/gis/install/geolibs/` och `sqlparse`

**Comment by Pajn** [comment]
När jag försökte göra en sökning så krävdes även modulen `django-filter`

**Comment by jh222xk** [comment]
Tack! Åtgärdat i: https://github.com/jh222xk/toerh/commit/2831d4d2fb3312dc4522570e6aa872a9c44ab06f
