### ISSUE TITLE
Lägga upp på publikt?

### ISSUE THREAD

**Issue by davidsoderberg** [jh222xk/toerh#5]
Hej, har du möjlighet att lägga upp sidan publikt? 
Då jag har krånglat med python innan och får inte det till att funka på den installation av dator jag har idag.

**Comment by jh222xk** [comment]
Hej!

Har du fortfarande inte fått igång det? Jag skulle kunna slänga upp det på en server om så önskas.

**Comment by davidsoderberg** [comment]
Det vore snällt då windows inte är min vän idag och verkar inte vilja bli det heller :disappointed:

**Comment by jh222xk** [comment]
Finns att besöka här: http://128.199.44.244:1337/

**Comment by davidsoderberg** [comment]
Tack :+1:
