### ISSUE TITLE
Registrering och inloggning direkt efter

### ISSUE THREAD

**Issue by davidsoderberg** [jh222xk/toerh#6]
Tycker det är bra att du loggar in användaren direkt efter att den har registrerat sig.
Man skulle kunna tänka sig att användaren måste bekräfta sin registrering via mejl och då bör du ta bort det med att den loggas in direkt efter registrering.

**Comment by jh222xk** [comment]
Ja precis, om man vill ha e-postverifiering så är det enkelt att bara plocka bort denna koden:

https://github.com/jh222xk/toerh/blob/master/accounts/views.py#L29-L44

och sedan implementera e-postverifiering.
