### ISSUE TITLE
Åtkomst till apiet

### ISSUE THREAD

**Issue by davidsoderberg** [jh222xk/toerh#8]
I din beskrivning så skriver du om att man skall använda curl för att komma åt det.
Det hade varit trevligt med en postman fil också så man kunde testa med det också.
Men bra att du beskriver hur man når det via curl till att börja med :+1:

**Comment by jh222xk** [comment]
Japp, cURL-instruktionerna är bara till för en fingervisning hur det går till, egentligen inga konstigheter hur man anropar API:et via exempelvis Postman när man har `Authorization: Token`.

**Comment by davidsoderberg** [comment]
Ja precis
